server:
  port: 8087
#  servlet:
#   context-path: /MSF

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/online_store
    username: root
    password: m79erXrA

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

feign:
  hystrix:
    enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
